# Generated by Django 3.2.9 on 2021-11-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='portada',
            name='orden',
            field=models.IntegerField(default=1),
        ),
    ]
