# Generated by Django 3.2.9 on 2021-11-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamano',
            name='descripcion',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
