# Generated by Django 3.2.9 on 2021-11-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_tamano_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tamano',
            name='precio_base',
            field=models.IntegerField(default=10000),
        ),
    ]
