# Generated by Django 3.2.9 on 2021-11-21 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_menutradicional'),
        ('pedidos', '0003_tamano_precio_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaTradicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.menutradicional')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pizza')),
            ],
        ),
    ]
