# Generated by Django 3.2.9 on 2021-11-21 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pizzatradicional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizzatradicional',
            options={'verbose_name_plural': 'Pizzas Tradicionales'},
        ),
    ]
