# Generated by Django 3.2.9 on 2021-11-21 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_menutradicional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menutradicional',
            options={'verbose_name_plural': 'Menú Tradicional'},
        ),
    ]
